# Generated by Django 2.1.3 on 2018-11-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('nickname', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('facebook', models.BooleanField()),
                ('apple', models.BooleanField()),
                ('google', models.BooleanField()),
                ('timeInGame', models.IntegerField()),
                ('numberOfSessions', models.IntegerField()),
                ('sessionTime', models.IntegerField()),
                ('level', models.IntegerField()),
                ('coins', models.IntegerField()),
                ('crystals', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('consumables', models.IntegerField()),
                ('skill', models.IntegerField()),
                ('payed', models.IntegerField()),
                ('paying', models.BooleanField()),
                ('banned', models.BooleanField()),
            ],
        ),
    ]
